### PR TITLE
Add health check make command

### PR DESCRIPTION
**Pull request by tylerwoonton**
I accidentally force pushed to #30 and broke the diff so I've duplicated the code here.

I'll sort out the tests because I know the previous MR was having trouble so we can get this merged this week.

### CODE REVIEW

**Comment by tylerwoonton** [comment]
Closes #28

**Comment by tylerwoonton** [comment]
I've tested this on PHP 7.4 in a Laravel 5.5 app and it all works as expected.

**Comment by tylerwoonton** [comment]
@miff2000 I'll ask someone to review this in the morning and then I'll merge it in.

**Review by Gman98ish — APPROVED** [review]
Looks good

**Comment by tylerwoonton** [comment]
Tagged at `v1.10.0`

https://github.com/ukfast/laravel-health-check/releases/tag/v1.10.0

**Pull request merged**
