### PR TITLE
Add HEALTH_CHECK_CHECKS to pass checks names as env value

### PR DESCRIPTION
**Pull request by idsulik**
Add `HEALTH_CHECK_CHECKS` env to have ability to pass checks names as env value, for example:
```dotenv
HEALTH_CHECK_CHECKS=log,redis,database
```

Check name should be bound to class with prefix `hc_` to avoid collision, for example:
```php
//ServiceProvider.php
$this->app->bind('hc_log', LogHealthCheck::class);
$this->app->bind('hc_redis', RedisHealthCheck::class);
$this->app->bind('hc_database', DatabaseHealthCheck::class);
```

p.s. it's fully backward compatible

### CODE REVIEW

**Comment by Gman98ish** [comment]
Cheers for the PR. I'm not 100% sure I see the use for this. The point of the health check package is that it can determine the availability of all the services you need for the app to run. So having that dependent on a .env check sort of defeats the point.

I see where you're going with it but it'll make it harder for users to add their own checks, and I'm not sure I see the benefit for all the added complexity

**Comment by idsulik** [comment]
> Cheers for the PR. I'm not 100% sure I see the use for this. The point of the health check package is that it can determine the availability of all the services you need for the app to run. So having that dependent on a .env check sort of defeats the point.
> 
> I see where you're going with it but it'll make it harder for users to add their own checks, and I'm not sure I see the benefit for all the added complexity

it can be useful when you want test app container and console container both of the containers use one image.  
so in docker or kubernetes you can path env of what you want to test. in console - rabbimtq/redis, in app - everything.  

Yes, it can be done with new console command with args `--only` but it's different approach via environment values

**Comment by Gman98ish** [comment]
Ah right I see what you mean now. As you've pointed out, you can sort of achieve this behaviour using #44 , or by doing .env checks in the config file. It's a good PR, I just don't think it's the direction we want to take the package in.

**Comment by tylerwoonton** [comment]
Yeah, I agree with @Gman98ish here. 

I'm going to close this MR, but I'm looking forward to getting #44 into the package when it's ready. 

Like we've said, feel free to tag us or open an issue if you have any questions! 👍🏻

**Comment by idsulik** [comment]
Okay)

**Pull request closed without merging**
